[deploy]
# Railway does not natively support apt packages in railway.toml, but you can use the NIXPACKS_INSTALL variable to install system packages.
# This will install libmagic1 before your app starts.

[env]
NIXPACKS_PKGS = "libmagic"